import json, datetime, re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
BLIND = json.loads((ROOT/'research/blind_set/questions.json').read_text(encoding='utf-8'))['questions']
Q = {q['id']:q for q in BLIND}
URLS = {
'sg': 'https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html',
'rolesanywhere': 'https://docs.aws.amazon.com/rolesanywhere/latest/userguide/getting-started.html',
'keypolicy': 'https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html',
'rotation': 'https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html',
'scp': 'https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html',
'ecrcrypto': 'https://docs.aws.amazon.com/AmazonECR/latest/userguide/encryption-at-rest.html',
'ecrscan': 'https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html',
'rdstls': 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html',
'albtls': 'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html',
'gd': 'https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-ec2.html',
'orgtrail': 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-trail-organization.html',
'ebs': 'https://docs.aws.amazon.com/ebs/latest/userguide/ebs-encryption-requirements.html',
'rdsconfig': 'https://docs.aws.amazon.com/config/latest/developerguide/rds-instance-public-access-check.html',
'configevent': 'https://docs.aws.amazon.com/config/latest/developerguide/monitor-config-with-cloudwatchevents.html',
'alblog': 'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-logs.html',
'pentest': 'https://aws.amazon.com/security/penetration-testing/',
'sqs': 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/troubleshooting-access-denied.html',
'role': 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html',
'guard': 'https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-guard.html',
'rulegen': 'https://docs.aws.amazon.com/cfn-guard/latest/ug/cfn-guard-rulegen.html',
'waf': 'https://docs.aws.amazon.com/waf/latest/developerguide/how-aws-waf-works-resources.html',
'crossrole': 'https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html',
'cfheaders': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/modifying-response-headers.html',
'edge': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html',
'ddb': 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.usagenotes.html',
'import': 'https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html',
'trailbucket': 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html',
'cforigin': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/restrict-access-to-load-balancer.html',
'catalog': 'https://docs.aws.amazon.com/servicecatalog/latest/adminguide/constraints-launch.html',
'athenatrail': 'https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html',
'athenaflow': 'https://docs.aws.amazon.com/athena/latest/ug/vpc-flow-logs.html',
'metricfilter': 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html',
'suppress': 'https://docs.aws.amazon.com/guardduty/latest/ug/findings_suppression-rule.html',
's3config': 'https://docs.aws.amazon.com/config/latest/developerguide/s3-default-encryption-kms.html',
'oidc': 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html',
'hsm': 'https://docs.aws.amazon.com/kms/latest/developerguide/keystore-cloudhsm.html',
'iamlogic': 'https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html',
'lock': 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html',
'ops': 'https://docs.aws.amazon.com/systems-manager/latest/userguide/OpsCenter-getting-started-sns.html',
'lambda': 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html',
'anomaly': 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html',
'fis': 'https://docs.aws.amazon.com/fis/latest/userguide/stop-conditions.html',
'cfstandard': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/standard-logging.html',
'cflogfields': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/standard-logs-reference.html',
'cfrealtime': 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/real-time-logs.html',
'externalid': 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html',
}
rows=[]
def add(n, answer, why, reasons, refs, tip, notes='', status='verified', confidence='high', candidates=None):
    q=Q[f'Q{n:03}']; now=datetime.datetime.now(datetime.timezone.utc).isoformat()
    stem=' '.join(b.get('text','') for b in q['stem'])
    kw=[]
    for phrase in re.findall(r'MOST securely|LEAST operational overhead|temporary security credentials|least privilege|customer managed key|noncompliant|near-real-time|near real time|CloudFormation|Amazon CloudFront|AWS CloudTrail|AWS KMS|CloudWatch Logs|AWS Organizations|Session Manager|OpenID Connect|DDoS|Application Load Balancer|Network Load Balancer',stem):
        if phrase not in kw: kw.append(phrase)
    refs_obj=[{'id':k,'url':URLS[k],'accessed_at':now,'claim':why,'basis':'Primary AWS documentation opened during this independent pass; option-specific inferences are recorded below.'} for k in refs]
    rows.append({'question_id':q['id'],'content_hash':q['content_hash'],'recorded_at':now,
      'independent_answer':list(answer) if answer is not None else None,'candidate_answers':candidates or [],'status':status,'confidence':confidence,
      'correct_explanation_vi':why,'option_reviews':[{'unit_id':c['id'],'letter':c['letter'],'verdict':'selected' if answer and c['letter'] in answer else 'not_selected_or_unresolved','reason_vi':reason,'reference_ids':refs} for c,reason in zip(q['choices'],reasons)],
      'references':refs_obj,'keywords':kw[:3],'memory_tip_vi':tip,'source_issues':notes,'option_count':len(q['choices'])})
    assert len(reasons)==len(q['choices']),q['id']

add(109,'A','A giới hạn web chỉ nhận từ ALB, DB chỉ nhận từ web/bastion và SSH chỉ từ IP công ty.',[
'A mở đúng luồng ALB → web → DB và nguồn SSH công ty.','B thiếu đường bastion → DB và nguồn SSH công ty.','C chỉ cho SSH từ CIDR VPC, không đáp ứng workstation công ty đã nêu.','D mở web cho toàn Internet thay vì giới hạn sgLB.'],['sg'],'Nếu có nhiều tầng, giới hạn SG theo tầng gọi trực tiếp; SSH theo nguồn quản trị.')
add(110,'A','Roles Anywhere dùng chứng chỉ X.509 và trust anchor để cấp credentials tạm thời cho workload ngoài AWS.',[
'A dùng đúng cơ chế Roles Anywhere và service principal.','B gán trust anchor cho IAM federation chung và sai service principal.','C assignment ứng dụng cho người dùng không cấp workload credentials theo cơ chế nêu trong đề.','D ứng dụng customer managed cho nhóm người dùng không thay thế Roles Anywhere cho workload.'],['rolesanywhere','role'],'Nếu workload ngoài AWS có PKI, cân nhắc Roles Anywhere; kiểm tra trust policy.')
add(111,'CD','SCP deny vẫn thắng IAM allow; bỏ quyền cho account sử dụng IAM policies trong key policy cũng khiến IAM allow mất hiệu lực.',[
'A Organizations dùng SCP/RCP, không gắn IAM identity policy lên account như mô tả.','B rotation giữ key identity và dữ liệu cũ vẫn giải mã được.','C SCP deny KMS có thể chặn quyền của instance role.','D xóa delegation cho IAM trong key policy có thể làm IAM permissions không đủ.','E cấp quyền RevokeGrant không đồng nghĩa đã thu hồi grant; ứng dụng đang dùng IAM permissions.'],['scp','keypolicy','rotation'],'Nếu IAM allow mà KMS vẫn deny, kiểm tra SCP và key policy trước.')
add(112,'B','Encryption configuration của ECR không đổi sau khi tạo repository; tạo lại với KMS rồi bật image scanning đáp ứng cả hai yêu cầu.',[
'A không thể đổi encryption repository hiện có theo cách mô tả.','B tạo repository mã hóa KMS và dùng scan report để phân tích CVE.','C có scanning nhưng inventory report không phải kết quả CVE; B trực tiếp cung cấp scan report.','D vừa không đổi được encryption hiện có vừa không dùng Trusted Advisor làm ECR image CVE scanner.'],['ecrcrypto','ecrscan'],'Nếu cần đổi ECR encryption, tạo repository mới; đọc image scan report.',confidence='medium',notes='C cũng bật scanning, nên có thể đáp ứng khả năng quét; B là lựa chọn trực tiếp sử dụng scan report. Đề không có tiêu chí MOST/LEAST để loại mọi phần thừa một cách tuyệt đối.')
add(113,'A','A dùng TLS cho các đường truyền và encryption cho RDS/EBS, tránh phần quản lý HSM và client-side encryption.',[
'A đáp ứng các lớp mã hóa nếu ALB → EC2 được cấu hình HTTPS.','B Secrets Manager lưu secrets, không tự mã hóa dữ liệu ứng dụng client-side.','C thêm HSM và quản lý mã hóa client-side, tăng chi phí và vận hành.','D truyền HTTP đến origin nên không bảo vệ toàn bộ dữ liệu in transit.'],['albtls','rdstls'],'Nếu cần mã hóa end-to-end, kiểm tra riêng từng hop và từng nơi lưu.',notes='A cần HTTPS target group; chỉ cài certificate chưa tự bật TLS. ALB không validate chứng chỉ target, nên self-signed có thể dùng cho hop này.')
add(114,'C','Process, DNS mining domains và outbound flows là bằng chứng trực tiếp để kiểm chứng hoạt động mining và phạm vi kết nối.',[
'A CPU/tactic/role chỉ là dấu hiệu hoặc ngữ cảnh, chưa xác nhận tiến trình mining.','B số findings và launch time không xác nhận hành vi mining.','C kiểm tra tiến trình, đích DNS và traffic liên quan mining.','D Session history, DNS records và severity không thay thế kiểm tra tiến trình/kết nối.'],['gd'],'Nếu điều tra mining, đối chiếu process + mining destination + network flow.',notes='Process details phụ thuộc finding/data source; nếu finding không có process, lấy telemetry host bổ sung, không khẳng định mọi GuardDuty finding đều có.')
add(115,'C','Organization trail áp dụng cho management/member accounts và tự bắt đầu logging cho account mới gia nhập.',[
'A trail đơn lẻ và notification không tự phủ mọi account mới.','B function ở từng account chưa xử lý tự động onboarding account mới như organization trail.','C management account có thể đổi trail hiện có thành organization trail.','D SCP chống stop/delete không tạo trail đang thiếu.'],['orgtrail'],'Nếu cần CloudTrail cho account hiện tại và tương lai, dùng organization trail.')
add(116,'C','C sửa quyền dùng KMS key, phù hợp lỗi khởi chạy encrypted AMI; Encrypt/Decrypt không phải danh sách quyền đầy đủ cho mọi trường hợp.',[
'A DescribeImages chỉ xem metadata, không cho giải mã EBS.','B StartInstances không sửa quyền KMS của encrypted root volume.','C là hướng xử lý KMS phù hợp; vẫn kiểm tra CreateGrant và quyền EBS cần thiết.','D DescribeKey chỉ xem key metadata, không cấp Decrypt/CreateGrant.'],['ebs'],'Nếu encrypted AMI khởi chạy rồi terminate, kiểm tra KMS key policy, grants và SCP.',confidence='medium',notes='Không khẳng định chỉ kms:Encrypt/kms:Decrypt luôn đủ. EBS còn cần CreateGrant, DescribeKey, GenerateDataKeyWithoutPlaintext, ReEncrypt theo ngữ cảnh; đề không nêu quyền sẵn có.')
add(117,'BCE','Config rule phát hiện DB instance public; EventBridge bắt compliance change và gửi SNS notification.',[
'A RDS event notification không phải direct Lambda target như mô tả và không cần Lambda để Config ghi nhận thay đổi.','B managed rule kiểm tra publiclyAccessible của DB instance.','C SNS là target gửi thông báo cho security engineer.','D RDS không post trực tiếp vào SQS theo luồng này; chiều SNS → SQS cũng không gửi ngược từ SQS.','E EventBridge nhận compliance change của Config rule.','F event flow Lambda → Config không phải luồng managed rule chuẩn cần chọn.'],['rdsconfig','configevent'],'Nếu báo vi phạm Config, nghĩ Config → EventBridge → SNS.',notes='Managed rule này kiểm tra DB instances; nếu hiểu all RDS resources gồm public snapshots thì cần thêm rules. Không quảng cáo một rule phủ mọi loại tài nguyên RDS.')
add(118,None,'A và D đều khả thi với tài liệu hiện hành: ALB đã hỗ trợ CloudWatch Logs; S3/Athena/visualization vẫn hợp lệ.',[
'A hiện có ALB → CloudWatch Logs và Logs Insights; không còn sai vì ALB chỉ hỗ trợ S3.','B không có native direct ALB log destination Redshift như mô tả.','C không có native direct ALB log destination OpenSearch như mô tả.','D S3 logs + Athena + visualization đáp ứng yêu cầu.'],['alblog','athenatrail'],'Nếu đề dùng từ directly, tra destination hiện hành trước khi loại.',status='ambiguous',confidence='high',candidates=[['A'],['D']],notes='Không khẳng định ngày ra mắt nếu chưa đối chứng release note; tính năng hiện hành được xác nhận trực tiếp bằng ALB docs.')
add(119,'AC','Port scan tài nguyên thuộc quyền quản lý và SQL injection test ứng dụng trên các service được phép phù hợp policy; các hành vi flooding/namespace/DNS nêu còn lại bị cấm.',[
'A port scanning VPC của công ty được phép trong phạm vi tài nguyên được quản lý.','B brute force S3 namespace là hành vi bucket walking bị cấm.','C kiểm thử SQL injection ứng dụng của công ty/RDS nằm trong phạm vi được phép.','D packet flooding không thuộc bài pentest thông thường được phép.','E DNS zone walking Route 53 là hoạt động bị cấm.'],['pentest'],'Nếu pentest AWS, kiểm tra permitted services và prohibited activities hiện hành.')
add(120,'BE','Kiểm tra queue policy deny và role IAM allow giữ least privilege, thay vì cấp toàn quyền để thử.',[
'A không gắn MFA device trực tiếp vào IAM role như IAM user.','B explicit deny trong queue policy có thể chặn role.','C role không có access key dài hạn gắn trực tiếp; EC2 dùng temporary credentials.','D SQSFullAccess mở rộng quyền quá mức và không thắng explicit deny.','E role cần identity permissions phù hợp với queue/action.'],['sqs','role'],'Nếu SQS AccessDenied, kiểm tra identity allow + resource deny + KMS/SCP khi có.')
add(121,None,'B là thiết kế dự định phù hợp nhưng ghi lệnh cm-guard không tồn tại; lệnh AWS công bố là cfn-guard validate.',[
'A validate-template kiểm tra template, không tự đánh giá các standards bảo mật tùy chỉnh.','B Guard trong CI/CD phù hợp sau khi sửa cm-guard thành cfn-guard; nguyên văn chưa chạy đúng.','C thêm EC2/queue và workflow triển khai riêng, tăng vận hành và thay đổi luồng delivery.','D review thủ công standards mới làm chậm delivery.'],['guard'],'Nếu kiểm tra IaC trước deploy, dùng Guard validate trong pipeline; đừng nhầm validate-template.',status='ambiguous',confidence='high',candidates=[['B']],notes='Typo thực thi cụ thể trong option B; không âm thầm sửa đề khi gọi đáp án verified.')
add(122,None,'AWS WAF không attach trực tiếp NLB; Count là cách thử rate rule ở resource được hỗ trợ, nhưng không giải quyết tiền đề NLB.',[
'A Count giúp quan sát rate nhưng WAF không attach trực tiếp NLB.','B Block có thể chặn legitimate traffic khi chưa xác định ngưỡng và vẫn không attach NLB.','C WAF không có rule action Monitor như mô tả.','D Allow không dùng để đo ngưỡng rồi rate-block bảo vệ NLB.'],['waf'],'Nếu WAF + NLB, kiểm tra resource support; Count chỉ áp dụng sau khi chọn kiến trúc hỗ trợ.',status='ambiguous',confidence='high',candidates=[['A']],notes='Không thay NLB thành ALB trong đề để hợp thức hóa A.')
add(123,'B','Guard rulegen tạo rules ban đầu từ các template đã biết compliant, sau đó validate trong pipeline.',[
'A drift detection kiểm tra tài nguyên đã triển khai, không sinh pre-deploy policy rules.','B rulegen sinh rules từ mẫu compliant; vẫn cần rà và test rules trước khi enforce.','C Detective không phân tích template thành rules tuân thủ IaC.','D chỉ đọc và tìm overlap chưa tạo validation/enforcement theo mô tả.'],['rulegen','guard'],'Nếu có mẫu IaC compliant, rulegen khởi tạo rules; review trước enforce.')
add(124,'AC','Cross-account AssumeRole cần permission phía caller và trust policy của role phía target; permissions cho tài nguyên của target role vẫn phải được cấu hình.',[
'A phù hợp nếu in the AWS account được hiểu là target của sts:AssumeRole; policy phải gắn IAM user tại caller account.','B SCP target không trực tiếp ràng buộc external IAM caller; source SCP và target role permissions phải kiểm tra đúng giai đoạn.','C role target cần trust caller.','D mô tả trust chung chung không thay thế identity permission phía caller.','E role caller không thay thế việc cho IAM user assume role target.'],['crossrole','scp'],'Nếu AssumeRole cross-account, kiểm tra caller permission + target trust.',confidence='medium',notes='A có cách viết dễ hiểu nhầm vị trí tạo policy. Không thể gắn policy target account vào IAM user caller như một managed-policy ARN cross-account.')
add(125,'B','Roles Anywhere cấp credentials tạm từ certificate cho partner ngoài AWS và role chỉ cho Session Manager.',[
'A tạo access keys dài hạn, thêm rủi ro so với certificate và temporary credentials.','B dùng trust anchor/profile/role để cấp temporary credentials cho Session Manager.','C mở SSH, trái yêu cầu Session Manager only.','D ARN/IP không tự cấp identity credentials và dùng EC2 Instance Connect thay Session Manager.'],['rolesanywhere','role'],'Nếu partner không có AWS account, certificate + Roles Anywhere có thể cấp temporary credentials.',confidence='medium',notes='Trust anchor là resource riêng; trust policy tham chiếu ARN/CA constraints, không tạo trust anchor bên trong JSON policy.')
add(126,'CD','CloudFront giảm latency; Lambda@Edge thêm security headers mà không sửa application code.',[
'A API cache không trực tiếp bổ sung HTTP security headers và CDN delivery cho cả hai origin như yêu cầu.','B Lambda authorizer kiểm soát authorization, không sửa origin response headers theo mô tả.','C Lambda@Edge có thể sửa headers ở response event.','D CloudFront phục vụ EC2/S3 origins qua edge locations.','E Connection header là hop-by-hop, không cung cấp bộ security headers yêu cầu.'],['edge','cfheaders'],'Nếu cần security headers ở edge, dùng response headers policy hoặc Lambda@Edge theo lựa chọn.',notes='Response headers policy hiện là giải pháp không cần code tốt cho nhiều trường hợp, nhưng không có trong options; không tự đổi khóa sang lựa chọn mới.')
add(127,'A','Customer managed KMS key hỗ trợ imported material; DynamoDB hỗ trợ dùng key đó cho encryption at rest.',[
'A nhập material từ HSM vào customer managed key, cấp quyền và chọn cho table.','B disable key khiến DynamoDB mất khả năng decrypt table key khi cache hết hạn.','C không import material vào AWS managed key do bạn không quản lý.','D không import AWS managed key; disable cũng phá encryption-at-rest dependency.'],['ddb','import'],'Nếu BYOK cho DynamoDB, dùng customer managed KMS key với imported material và giữ key usable.')
add(128,'C','Bucket policy phải cho CloudTrail ghi đúng prefix mới trước khi cập nhật prefix của trail.',[
'A tạo/xóa trail không cần thiết và có thể thất bại vì prefix policy chưa phù hợp.','B PutBucketPolicy cho engineer không sửa resource prefix được cho CloudTrail write.','C sửa bucket policy prefix rồi sửa trail prefix đúng luồng AWS hướng dẫn.','D GetBucketPolicy không cấp CloudTrail PutObject vào prefix mới.'],['trailbucket'],'Nếu đổi CloudTrail prefix, cập nhật S3 policy resource prefix trước.')
add(129,'BC','CloudFront chèn origin custom header bí mật; ALB chỉ forward khi header/value khớp và chặn mặc định phần còn lại.',[
'A cache key policy không tự tạo origin secret header.','B Origin Custom Headers tạo header cho request tới ALB.','C ALB listener condition kiểm header và default action phải chặn phần còn lại.','D X-Forwarded-For không chứng minh request đến từ distribution của bạn.','E certificate chung không hạn chế đường direct-to-ALB.'],['cforigin'],'Nếu chặn bypass CloudFront, dùng secret origin header + ALB rule; giữ secret và dùng HTTPS.')
add(130,'C','Service Catalog cung cấp sản phẩm với AMI đã duyệt; giới hạn permission để developer chỉ provision catalog trong account development.',[
'A template được cung cấp không ngăn developer dùng API/AMI khác.','B cài thêm software sau launch không ngăn AMI chưa duyệt hoặc loại bỏ software cũ.','C catalog + permissions giới hạn launch vào sản phẩm/account được phê duyệt.','D StackSets mọi account trái yêu cầu chỉ development account.'],['catalog'],'Nếu chỉ được launch mẫu đã duyệt, dùng Service Catalog kèm IAM/launch constraints.')
add(131,'D','Cả hai loại log có thể lưu S3; Athena truy vấn dữ liệu lịch sử sau incident.',[
'A metric filter tạo numeric metrics theo dữ liệu mới, không phải truy vấn log lịch sử.','B subscription filter chuyển luồng log, không phải công cụ truy vấn sau incident.','C không có native direct log destination DynamoDB cho cả hai service như mô tả.','D S3 và Athena hỗ trợ truy vấn CloudTrail/VPC Flow Logs.'],['athenatrail','athenaflow','metricfilter'],'Nếu query log lịch sử trên S3, dùng Athena; metric/subscription filter có mục đích khác.')
add(132,'C','Suppression rule hẹp archive finding false positive mà GuardDuty vẫn tiếp tục tạo finding và giữ archived view.',[
'A không có thao tác tắt một FTP rule như mô tả.','B trusted IP list rộng có thể che các findings khác và không chọn chính xác hành vi false positive.','C suppression theo finding/resource cụ thể giảm noise, vẫn giữ archived findings.','D GuardDuty không có API xóa findings tùy ý như mô tả; dùng archive/suppress.'],['suppress','gd'],'Nếu suppress false positive, scope theo finding + resource cụ thể; tránh rule quá rộng.',confidence='medium',notes='Suppressed findings không gửi EventBridge/Security Hub và không dùng trong attack-sequence correlation. GuardDuty docs không có finding FTP brute-force tương ứng tiền đề; không khẳng định visibility hoàn toàn không đổi.')
add(133,'B','Custom Config Lambda rule kiểm tra tag và xác nhận customer managed KMS key. A ghi tag như rule parameter, trong khi managed rule chỉ có kmsKeyArns; tag phải đặt ở scope.',[
'A tag không phải parameter của s3-default-encryption-kms; thiết kế này khả thi nếu sửa tag sang Config scope, nhưng không đúng nguyên văn.','B custom rule có thể đọc tag/encryption và xác nhận KMS customer managed key.','C Inspector không scan S3 bucket default encryption như một Config rule.','D Trusted Advisor không có custom-policy-rule facility như mô tả.'],['s3config'],'Nếu Config managed rule thiếu tag parameter, đặt tag ở scope; custom rule khi cần logic khác.',notes='Không nói managed rule không hỗ trợ tag filtering nói chung: Config scope hỗ trợ tag. B phải kiểm tra customer managed/key ARN, không chỉ SSE-KMS bật.')
add(134,'A','IAM OIDC provider và role trust policy cho phép external OIDC principal lấy temporary credentials qua web identity federation.',[
'A thiết lập đúng OIDC federation và trust target role.','B Roles Anywhere trust anchor dùng X.509/CA, không dùng OIDC token.','C Identity Center application assignment không thay IAM OIDC role federation cho repository workload.','D RAM share không tạo OIDC trust provider.'],['oidc','rolesanywhere'],'Nếu CI bên ngoài phát OIDC token, IAM OIDC provider + role trust; giới hạn aud/sub.')
add(135,'D','KMS custom key store trên CloudHSM giữ tích hợp KMS và key material riêng; cluster cần ít nhất hai active HSM ở hai AZ.',[
'A một HSM không đáp ứng yêu cầu custom key store lúc tạo và HA.','B EC2/open-source material upload không tạo CloudHSM-backed KMS custom key store theo mô tả.','C HMAC dùng MAC, không thay symmetric encryption key cho integration này.','D hai HSM phù hợp khi đặt ở các AZ khác nhau và cấu hình KMS crypto user/key store.'],['hsm'],'Nếu KMS APIs + HSM riêng + HA, CloudHSM custom key store với >=2 active HSM khác AZ.',notes='D nói hai HSM nhưng không chỉ rõ khác AZ; triển khai phải thêm điều kiện này, không khẳng định hai HSM cùng AZ là HA.')
add(136,'D','Root SCP explicit deny ses:* chặn SES dù IAM và OU SCP allow; phải gỡ deny ở root.',[
'A resource allow không thắng root SCP deny.','B IAM group không là resource-policy principal và không thắng SCP deny.','C đề không nêu Control Tower guardrail gây lỗi; deny có sẵn ở root SCP.','D bỏ SES explicit deny khỏi root SCP giải quyết restriction đã cho.'],['iamlogic','scp'],'Nếu OU allow nhưng vẫn deny, kiểm tra SCP ở mọi ancestor; explicit deny thắng.')
add(137,'AD','Organization trail tập trung log ít vận hành; Object Lock compliance giữ từng log version trong hai năm.',[
'A đặt retention compliance và cho trail management account context ghi vào bucket security là hướng phù hợp.','B chỉ cho member-account principals write không thay service-principal policy của organization trail.','C lifecycle expiration không ngăn xóa/chỉnh log trước hai năm.','D organization trail tập trung member activity vào security bucket.','E per-account trails và Lambda/Firehose tăng vận hành, không tự cấu hình WORM retention.'],['orgtrail','trailbucket','lock'],'Nếu log bất biến hai năm, organization trail + Object Lock compliance; bucket policy cho CloudTrail service.',confidence='medium',notes='Bucket policy thực tế phải cho cloudtrail.amazonaws.com với SourceArn management/delegated trail, không chỉ cho IAM principal management account. CloudTrail không log mọi data event mặc định; cần chọn event coverage theo yêu cầu.')
add(138,'C','OpsItem lưu incident và thông báo khi tạo/cập nhật; Automation runbook có thể đóng port và tái dùng cho incident sau.',[
'A Lambda có thể đóng port/log và SNS gửi alert đầu tiên, nhưng mô tả chưa có incident-progress updates/work item.','B remediation thủ công không đạt automated future response.','C OpsCenter + notifications + runbook quản lý vòng đời incident và đóng port.','D Inspector tạo findings, không tự đóng port bằng cấu hình alarm như mô tả.'],['ops'],'Nếu cần cập nhật tiến độ incident, dùng OpsItem lifecycle notifications và Automation.',confidence='medium',notes='C cần cấu hình thực thi runbook tự động; association runbook vào OpsItem đơn thuần chưa tự execute. A có thể được mở rộng để đáp ứng nhưng không mô tả progress updates.')
add(139,'AB','Lambda phải assume execution role và role đó phải có quyền ghi CloudWatch Logs.',[
'A execution-role trust phải cho lambda.amazonaws.com AssumeRole.','B execution role phải có logs:CreateLogGroup/CreateLogStream/PutLogEvents phù hợp.','C X-Ray traces không cấp CloudWatch Logs write.','D function resource policy kiểm invocation, không thay execution-role Logs permissions.','E developer role không phải role Lambda assume để ghi logs.'],['lambda'],'Nếu Lambda không ghi log, kiểm execution-role trust và Logs permissions.')
add(140,'B','Log metric filter tạo metric; anomaly threshold theo metric và SNS alarm gửi notification. Đây là numeric anomaly, không tự phát hiện mọi bất thường ngữ nghĩa trong log.',[
'A Container Insights thu thập logs/metrics nhưng option không nêu metric/filter nào biến application logs thành signal cần chấm.','B định nghĩa rõ log-derived metric, anomaly alarm và SNS.','C batch Athena/visualization không tự cung cấp near-real-time anomaly alarm theo mô tả.','D CloudTrail/Detective không dùng để học arbitrary EKS application-log anomalies qua App Mesh.'],['metricfilter','anomaly'],'Nếu anomaly trên số lượng log events, metric filter → anomaly alarm → SNS.',confidence='medium',notes='B chỉ phát hiện bất thường của metric được trích xuất. Nếu mục tiêu là log-pattern anomaly tùy ý, cần CloudWatch Logs anomaly detector; A cũng khả thi nếu bổ sung cấu hình signal, nên không nói Container Insights không thu app logs.')
add(141,'B','FIS tạo fault experiments có targeting và stop conditions dựa trên CloudWatch alarms để dừng khi vượt ngưỡng.',[
'A Express Step Functions không có cơ chế StopExecution như Standard, và không nêu stop guardrail thích hợp.','B FIS phù hợp; phải thêm CloudWatch stop condition vào experiment template.','C shutdown tuần tự thủ công kém realistic/automation và không định nghĩa stop condition.','D Automation runbook có thể dừng nhưng option không đưa fault experiment và stop conditions theo yêu cầu như FIS.'],['fis'],'Nếu thử lỗi production, FIS + CloudWatch stop conditions; dừng thử không tự hoàn tác mọi tác động.',confidence='medium',notes='Option B không viết stop condition; đây là cấu hình cần thêm khi triển khai, không tự có vì chỉ schedule experiment.')
add(142,None,'Không có option đầy đủ: standard logging v2 ghi IP và các fields được hỗ trợ, không tự ghi full headers; cs-headers thuộc real-time logs.',[
'A lấy viewer IP và một số header fields nhưng không full arbitrary headers chỉ bằng bật standard logging v2.','B sourceIp không bổ sung header information và có thể là IP hop trung gian theo luồng đề.','C PutLogEvents không thay đổi nội dung log fields.','D thêm headers vào cache key không bật logging và gây cache fragmentation.'],['cfstandard','cflogfields','cfrealtime'],'Nếu cần full headers, phân biệt standard với real-time logging; chọn fields và pipeline phù hợp.',status='ambiguous',confidence='high',candidates=[['A']],notes='Standard v2 có viewer-request/response-log-data bổ sung từ CloudFront Functions, nhưng cần code thêm và giới hạn 800 bytes; option A không nêu giải pháp này. Không chuyển cs-headers từ real-time sang standard bằng suy đoán.')
add(143,'C','Không có ExternalId theo customer, bên thứ ba có thể bị lừa assume role của Company A khi customer khác đưa role ARN đó.',[
'A trust không chứng minh target role không có resource permissions; đề nói role phục vụ ingest.','B trust Company B không cho customer account trực tiếp assume role.','C customer khác có thể đưa ARN của A cho Company B, tạo confused deputy.','D ExternalId là giá trị phân biệt customer do third party quản lý, không cho intercept request như mô tả.'],['externalid'],'Nếu third party assume role cho nhiều khách, trust third party + ExternalId riêng theo customer.',notes='Source dùng account IDs 10 digits như placeholders; account ID/ARN thật phải hợp lệ. Không sửa nguyên văn nguồn.')

assert len(rows)==35
out=HERE/'q109_q143';out.mkdir(exist_ok=True)
(out/'independent.json').write_text(json.dumps({'method':'Independent primary-doc review before reading existing per-question research. Root had previously seen aggregate audit notes for Q118/Q122/Q133/Q143 and source key Q143; therefore this group is NOT claimed fully blinded. No live AWS experiments. Technical validity distinguished from intended exam wording.','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'questions':rows},ensure_ascii=False,indent=2),encoding='utf-8')
print('Saved 35 independent records;',sum(len(x['option_reviews']) for x in rows),'options; existing per-question reviews not yet read.')
