import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent
BLIND = ROOT.parents[1] / 'blind_set' / 'questions.json'
qs = json.loads(BLIND.read_text(encoding='utf-8'))['questions'][:36]
now = datetime.now(timezone.utc).isoformat()
S = {}
def src(k, url, claim):
    S[k] = {'id': k, 'url': url, 'supported_claim': claim, 'access_date': now[:10], 'accessed_by': 'web.run; actual primary AWS page opened before conclusions persisted'}
src('lambda','https://docs.aws.amazon.com/lambda/latest/dg/permissions-source-function-arn.html','Lambda runtime calls use execution-role credentials; lambda:SourceFunctionArn is a different context key from aws:SourceArn.')
src('s3resource','https://docs.aws.amazon.com/AmazonS3/latest/userguide/security_iam_service-with-iam.html','Object operations such as GetObject require object ARNs; bucket ARN alone covers bucket operations.')
src('principal','https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html','IAM user, assumed-role session, and STS federated-user are distinct principals; Lambda function ARN is not an IAM principal.')
src('sts','https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html','GetSessionToken with serial number and token code produces MFA-authenticated temporary credentials.')
src('scp','https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_syntax.html','Deny with NotAction and StringNotEquals RequestedRegion restricts regions while exempting named global APIs; default FullAWSAccess permits unless denied.')
src('via','https://docs.aws.amazon.com/kms/latest/developerguide/conditions-kms.html','kms:ViaService restricts forward-access requests; SES and WorkMail are supported; Resource * in a key policy means the attached key.')
src('cognito','https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html','User pools issue JWT tokens; identity pools exchange identities for temporary AWS credentials.')
src('authorizer','https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html','HTTP API Lambda authorizers can evaluate authentication tokens before forwarding authorized requests.')
src('idp','https://docs.aws.amazon.com/singlesignon/latest/userguide/how-to-connect-idp.html','External IdP connection exchanges IAM Identity Center and IdP SAML metadata; identity source configuration includes connection settings.')
src('scim','https://docs.aws.amazon.com/singlesignon/latest/userguide/how-to-with-scim.html','Enable Identity Center automatic provisioning and obtain endpoint/token before configuring SCIM at external IdP; SCIM is distinct from SAML authentication.')
src('lock','https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html','Compliance retention cannot be bypassed by administrators/root during retention; governance can be bypassed with permission.')
src('replica','https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html','Object Lock replication requires enabled destination Object Lock and replicates retention metadata.')
src('delete','https://docs.aws.amazon.com/kms/latest/developerguide/deleting-keys.html','Multi-Region primary deletion waits for all replicas to be deleted; 7–30-day primary waiting period begins after replicas disappear.')
src('keystate','https://docs.aws.amazon.com/kms/latest/developerguide/key-state.html','PendingReplicaDeletion and PendingDeletion keys cannot perform cryptographic operations.')
src('ssm','https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html','Session Manager provides managed shell sessions without inbound SSH ports or SSH keys, including hybrid nodes.')
src('ssmssh','https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html','Actual SSH over Session Manager requires a public key/PEM already associated with the managed node.')
src('ssmprice','https://aws.amazon.com/systems-manager/pricing/','Pricing page explicitly records Advanced Instances Tier removal June 30, 2026, and hybrid Session Manager $0.05/session effective September 30, 2026; EC2 Session Manager has no additional charge.')
src('runtime','https://docs.aws.amazon.com/guardduty/latest/ug/runtime-monitoring.html','Runtime Monitoring analyzes OS, network, and file events using agent support; EKS Fargate is not supported.')
src('eks','https://docs.aws.amazon.com/guardduty/latest/ug/kubernetes-protection.html','EKS Protection analyzes EKS audit logs through an independent data stream.')
src('iotclient','https://docs.aws.amazon.com/iot/latest/developerguide/basic-policy-variables.html','Untrusted ClientId substitutions can broaden policy resources; ClientId self-reference does not bind a client to a trusted thing.')
src('iotthing','https://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-variables.html','ThingName policy variable requires associated authenticated principal and matching thing-name client ID.')
src('config','https://docs.aws.amazon.com/config/latest/developerguide/how-does-config-work.html','AWS Config configuration items describe resource configuration state and change history.')
src('daily','https://docs.aws.amazon.com/config/latest/APIReference/API_RecordingMode.html','Daily recording captures latest configuration change over 24 hours; continuous recording records changes as they occur.')
src('hsm','https://docs.aws.amazon.com/kms/latest/developerguide/keystore-cloudhsm.html','CloudHSM custom stores create symmetric AES-256 KMS key material in HSM and perform supported cryptographic operations there.')
src('pair','https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKeyPair.html','GenerateDataKeyPair cannot use a KMS key in a custom key store.')
src('kmsaudit','https://docs.aws.amazon.com/kms/latest/developerguide/logging-using-cloudtrail.html','CloudTrail logs AWS KMS API operations for auditing.')
src('cwagent','https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html','CloudWatch agent streams configured local logs and supports retention_in_days including 365; new groups default never-expire, existing retention must be checked.')
src('perimeter','https://docs.aws.amazon.com/whitepapers/latest/building-a-data-perimeter-on-aws/perimeter-implementation.html','Endpoint policies constrain all traversing principals; SCPs constrain organization principals; resource and principal organization keys implement data perimeters.')
src('pit','https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBClusterToPointInTime.html','PITR restores a new database cluster at a requested time within available retention.')
src('revokeidc','https://docs.aws.amazon.com/singlesignon/latest/userguide/revoke-user-permissions.html','Complete revocation includes deny/SCP, assignment removal and sessions; disabling a user alone does not invalidate already-issued role sessions.')
src('lake','https://docs.aws.amazon.com/awscloudtrail/latest/userguide/query-event-data-store.html','CloudTrail Lake SQL queries organizational event data stores for event history.')
src('inspector','https://docs.aws.amazon.com/inspector/latest/user/scanning-ec2.html','Inspector detects EC2 package vulnerabilities and network exposure; it does not patch them.')
src('patch','https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager.html','Patch Manager automates patch installation and patch compliance.')
src('maciedaily','https://docs.aws.amazon.com/macie/latest/user/discovery-asdd-how-it-works.html','Automated discovery evaluates representative supported S3 object samples daily; discovery jobs can inspect selected buckets more thoroughly.')
src('snapshot','https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/share-encrypted-snapshot.html','Encrypted snapshot sharing requires customer managed key access for recipient accounts; default AWS managed RDS key snapshots cannot be shared.')
src('mysql','https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Security.html','require_secure_transport=ON enforces TLS for Aurora MySQL.')
src('postgres','https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Security.html','Aurora PostgreSQL TLS enforcement uses rds.force_ssl, not require_secure_transport.')
src('wafrate','https://docs.aws.amazon.com/waf/latest/APIReference/API_RateBasedStatement.html','Current WAF rate-based Limit minimum is 10; evaluation windows include 300 seconds; rate limiting is approximate.')
src('nacl','https://docs.aws.amazon.com/vpc/latest/userguide/custom-network-acl.html','NACLs are stateless, evaluate lowest rule first, and TLS outbound return traffic requires inbound ephemeral ports.')
src('taskrole','https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html','Task IAM role provides AWS permissions to containers in a task; containers within the task are not a credential isolation boundary.')
src('rotate','https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html','Secrets Manager supports configured automated secret rotation, including RDS integration.')
src('vpce','https://docs.aws.amazon.com/kms/latest/developerguide/vpce-policy-condition.html','KMS policy aws:SourceVpce identifies endpoint; SourceIp is not usable to identify requests through interface endpoints.')
src('dns','https://docs.aws.amazon.com/kms/latest/developerguide/vpce-connect.html','KMS interface endpoints with private DNS resolve normal KMS endpoint names to private endpoint addresses.')
src('revokerole','https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_revoke-sessions.html','Role-session revocation attaches a deny for temporary credentials issued before the revocation time.')
src('ssekms','https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html','Reading SSE-KMS objects requires S3 access and KMS decrypt authorization; customer managed keys allow separate key policy control.')
src('gdsource','https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_data-sources.html','GuardDuty collects its foundational sources independently; DNS monitoring requires AWS resolver rather than a custom DNS resolver.')
src('gdhub','https://docs.aws.amazon.com/guardduty/latest/ug/securityhub-integration.html','GuardDuty automatically sends findings when Security Hub integration is enabled by both services.')
src('gdevent','https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_eventbridge.html','GuardDuty findings can trigger EventBridge targets, including SNS notifications.')
src('cognitopwd','https://docs.aws.amazon.com/cognito/latest/developerguide/managing-users-passwords.html','User-pool password policy controls Cognito local users and already has a minimum-length constraint.')
src('iampwd','https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_account-policy.html','IAM account password policies govern IAM users, not federated users authenticated by an external IdP.')
src('macieorg','https://docs.aws.amazon.com/macie/latest/user/accounts-mgmt-ao.html','Organizations Macie delegated administrator centrally manages discovery and findings in member accounts.')
src('maciepublish','https://docs.aws.amazon.com/macie/latest/user/findings-publish-frequency.html','Publishing sensitive-data findings to Security Hub is opt-in, configured per account and Region; default publication concerns policy findings.')
src('macie','https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html','Macie discovers sensitive S3 data with managed identifiers; findings integrate with EventBridge for SNS notification.')
src('string','https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-string-match.html','WAF string match rules can match HTTP header values including User-Agent.')
src('sqli','https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-sqli-match.html','WAF SQL injection statements inspect request components for SQL injection patterns.')
src('wafresources','https://docs.aws.amazon.com/waf/latest/developerguide/how-aws-waf-works-resources.html','WAF associates with supported resources including ALB and CloudFront, not a bare EC2 instance.')
src('sg','https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html','Security group rules allow traffic and cannot express deny rules or inspect HTTP headers.')
src('host','https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html','After host key rotation, manually run eic_harvest_hostkeys to update the EC2 Instance Connect trusted host-key database.')
src('ctinsight','https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-insights-events-with-cloudtrail.html','CloudTrail Insights detects unusual API write-call rates against a baseline; user attribution requires investigation of underlying events.')
src('hubinsight','https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-custom-insights.html','Custom insights group/filter findings; this is not itself sequential multi-stage attack correlation.')
src('hubevent','https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-all-findings.html','Security Hub finding events can trigger EventBridge and Lambda remediation.')
src('flow','https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-cwl.html','VPC Flow Logs in CloudWatch describe traffic with address, time, and bytes fields for queries.')
src('metrics','https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html','Metric filters extract log events and dimensions for counters and alarms.')

# All conclusions below were fixed from blind content and primary documents before any review/key was read.
D = {}
def put(n, ans, status, explanation, reasons, sources, keywords, tip, issues='', candidates=None):
    D[f'Q{n:03}'] = dict(independent_answer=ans,status=status,explanation=explanation,reasons=reasons.split('|'),source_ids=sources.split(),keywords=keywords.split('|'),conditional_tip=tip,source_issues=issues,candidates=candidates)
put(1,None,'ambiguous','Không lựa chọn nào sửa đủ policy: GetObject cần ARN object, còn mã chạy trong Lambda dùng execution role, không phải service principal Lambda với SourceArn này. C chỉ sửa phần Resource và có thể là ý định của đề.', 'Sai: ARN function không phải IAM principal hợp lệ.|Sai: thêm action không sửa Resource object và principal.|Chưa đủ: /* sửa ARN object nhưng principal/điều kiện vẫn không cấp quyền cho execution role.|Sai: đảo principal và resource không cấp quyền đọc S3.', 'lambda s3resource principal','MyLambdaFunction|read the objects|bucket policy','Nếu Lambda gọi S3 bằng mã ứng dụng, kiểm tra execution role và ARN object cùng các điều kiện policy.','SourceArn thiếu Region/account; C có khoảng trắng trong ARN ảnh; không có đáp án đầy đủ.', ['C'])
put(2,['S1','S5','S3'],'ambiguous','User pool → app client → HTTP API Lambda authorizer là luồng xác thực bằng token phù hợp cho người dùng ngoài. Nếu temporary credentials nghĩa là thông tin xác thực AWS STS, đề còn thiếu identity pool.', 'Chọn trước: user pool quản lý danh tính và phát token.|Không cần cho xác thực người dùng: role cấp quyền AWS cho backend.|Chọn sau app client: authorizer kiểm tra token trước backend.|Sai: tự lưu mật khẩu theo microservice tăng quản trị.|Chọn sau user pool: app client định cấu hình ứng dụng dùng token.|Không phù hợp nhất: Identity Center phục vụ workforce, không thay user pool ứng dụng khách.', 'cognito authorizer','external users|temporary credentials|user databases','Nếu yêu cầu temporary AWS credentials, thêm Cognito identity pool; nếu chỉ token JWT, dùng user pool/app client/authorizer.','Không xác định loại temporary credentials; Lambda authorizer hợp lệ nhưng native JWT authorizer có thể ít quản trị hơn.', ['S1','S5','S3'])
put(3,'B','verified','Dùng GetSessionToken kèm serial MFA và mã OTP, rồi dùng bộ thông tin xác thực tạm thời trả về cho CLI. Đổi điều kiện deny sang true sẽ đảo mục tiêu bảo vệ.', 'Sai: true sẽ deny phiên MFA.|Đúng: token tạm thời xác thực MFA đáp ứng policy.|Có thể thiết kế MFA qua SAML nhưng cần federation/role mới, không phải sửa trực tiếp ít thay đổi nhất.|Không chọn: phương án nhắc NotAction không có trong policy ảnh và thêm role không cần thiết.', 'sts','multi-factor authentication|AWS CLI|Amazon EC2 commands','Nếu CLI bị deny bởi aws:MultiFactorAuthPresent, lấy và dùng thông tin xác thực tạm thời có MFA.','D tham chiếu NotAction không tồn tại; SAML/AssumeRole có thể là giải pháp khác nếu cấu hình đầy đủ.')
put(4,'C','verified','Deny với NotAction loại trừ các global service và StringNotEquals eu-west-1 chặn API ngoài Region cho OU. Explicit deny vẫn có hiệu lực khi SCP mặc định FullAWSAccess tồn tại.', 'Sai: StringEquals deny ngay Region được phép.|Sai: allow không hạn chế quyền đang được FullAWSAccess cho phép.|Đúng: deny ngoài eu-west-1, trừ global services đã liệt kê.|Sai: allow có điều kiện không tạo explicit deny ngoài Region.', 'scp','default SCP|eu-west-1|global services','Nếu OU đang có FullAWSAccess, dùng explicit deny ngoài Region với ngoại lệ global phù hợp.')
put(5,['S1','S3','S4'],'ambiguous','Nếu S1 bao gồm toàn bộ trao đổi SAML, cấu hình identity source → bật SCIM ở Identity Center → bật SCIM ở IdP là một chuỗi hợp lệ. Đề chỉ yêu cầu external IdP nên không chứng minh SCIM bắt buộc và không có một chuỗi ba bước duy nhất.', 'Hợp lệ: cấu hình external identity source, bao gồm kết nối SAML.|Sai: API endpoint của IdP không phải principal SAML trong trust policy.|Hợp lệ nếu dùng SCIM: lấy endpoint/token trước cấu hình IdP.|Hợp lệ nếu dùng SCIM: dùng endpoint/token từ Identity Center.|Hợp lệ và cần cho trao đổi SAML, không thể coi là distractor sai.|Hợp lệ và cần cho trao đổi SAML, không thể coi là distractor sai.', 'idp scim','identity provider|identity source|SAML metadata','Nếu cần tự động provision người dùng, cấu hình SAML trước rồi bật SCIM ở AWS trước IdP.','Lỗi chữ exlemai/specifics; SAML metadata là bước hợp lệ còn SCIM không được yêu cầu rõ; thứ tự ba slot mơ hồ.', ['S1','S3','S4'])
put(6,'C','verified','Policy chỉ cho ExampleRole dùng key gắn policy qua WorkMail hoặc SES ở us-west-2. Resource * trong key policy chỉ key này, không phải mọi key trong account.', 'Sai: role là principal được cấp quyền, không phải service nhận quyền do role cấp.|Sai: không quy định nội dung email hay owner mà giới hạn luồng gọi dịch vụ.|Đúng: role và ViaService/Region phải khớp.|Sai: * không mở rộng sang mọi customer managed key.', 'via','key policy|customer managed key','Nếu Resource * xuất hiện trong KMS key policy, đọc nó là key đang gắn policy.','SES và WorkMail đều có trong danh sách ViaService hiện hành.')
put(7,None,'ambiguous','B xác định đúng STS federated-user/Bob và dùng explicit deny, nhưng bucket ARN không bao phủ GetObject/DeleteObject. Cần cả bucket ARN và bucket/* để chặn toàn bộ truy cập dữ liệu như đề yêu cầu.', 'Sai: Allow không deny Bob.|Chưa đủ: đúng federated principal nhưng thiếu ARN object /*.|Sai: IAM user/Bob khác STS federated-user/Bob.|Sai: assumed-role session là loại principal khác.', 'principal s3resource','federated user|Bob|bucket policy','Nếu deny cả bucket và dữ liệu S3, liệt kê cả ARN bucket và ARN bucket/*.','Tất cả ảnh chỉ có bucket ARN, không đáp án đầy đủ cho object access.', ['B'])
put(8,{'P1':None,'P2':'R4','P3':'R3','P4':'R1','P5':None},'unresolved','P1 và P5 trùng nguyên văn nên cả hai phù hợp R5, trái quy tắc mỗi đáp án dùng một lần. P2→R4, P3→R3 và P4→R1 hợp lý; đề không có chiến lược riêng đủ để gán R2.', 'P1: phù hợp R5 vì bytes/destination/time, nhưng bị trùng P5.|P2: R4; metric filters đếm lỗi theo source IP trong một giờ.|P3: R3 gần nhất; Insights phát hiện tốc độ API bất thường, cần lọc CloudTrail để xác định privileged user/delete.|P4: R1; EventBridge/Lambda có thể cách ly instance theo finding.|P5: phù hợp R5 giống P1, không thể gán khác để hoàn thành one-use.|R1: cần tự động remediation, phù hợp P4.|R2: custom insights nhóm findings không tự chứng minh tương quan chuỗi tấn công; thiếu prompt riêng.|R3: P3 là gần nhất nhưng cần scope API và user bổ sung.|R4: P2 đếm xác thực thất bại theo IP.|R5: đồng thời P1 và P5, gây lỗi đề.', 'flow metrics ctinsight hubinsight hubevent','one time|multi-stage attacks|office hours','Nếu hai prompt trùng nhau mà đáp án chỉ dùng một lần, giữ trạng thái unresolved và sửa nguồn trước khi chấm.','Đã xem ảnh và xác nhận hàng 1/hàng 5 trùng; distances là typo instances; không ép một full mapping.')
put(9,'B','verified','Dùng Object Lock compliance và replication sang bucket đích đã bật Object Lock để sao chép retention. Trong thời hạn retention, ngay cả administrator/root cũng không xóa vĩnh viễn version được bảo vệ.', 'Sai: governance có thể bị bypass/gỡ bởi quyền phù hợp.|Đúng khi bucket đích bật Object Lock và replication retention.|Sai: ReplicateDelete không chặn admin trực tiếp xóa version.|Sai: versioning vẫn cho phép người có quyền xóa version.', 'lock replica','administrator access|secondary Region|permanently delete','Nếu phải chống cả administrator trong thời hạn lưu giữ, dùng compliance retention và bảo đảm bucket replica cũng bật Object Lock.')
put(10,'B','ambiguous','mrk- gợi ý multi-Region key: phải xóa mọi replica trước khi primary bắt đầu thời gian chờ tối thiểu 7 ngày. Tuy nhiên key đã scheduled deletion không thể vẫn enabled/usable như đề mô tả.', 'Sai: root không bỏ qua thời gian chờ hoặc dependency replica.|Phù hợp ý định: tìm và schedule các replica cùng key ID với 7 ngày.|Sai: thêm quyền kms:* không xử lý dependency replica.|Sai: 30 ngày làm chậm hơn và không xử lý replica.', 'delete keystate','multiple AWS Regions|enabled and usable|as quickly as possible','Nếu primary ở PendingReplicaDeletion, xóa replicas trước rồi tính thời gian chờ primary.','ARN chứa dấu ;, account ID và key ID có lỗi; enabled/usable mâu thuẫn state; không thể xóa ngay.', ['B'])
put(11,'B','ambiguous','Session Manager shell đáp ứng truy cập bảo trì không cần SSH key và không mở inbound port. SSH thực sự qua Session Manager vẫn cần key; tính phí theo machine-hours của đề không khớp pricing hiện hành.', 'Sai: bastion cần đường mạng và quản trị SSH keys.|Gần nhất: Session Manager shell, nhưng không thỏa literal SSH không key và machine-hours.|Sai: CloudShell không tự cung cấp truy cập riêng tới máy EC2/on-premises.|Sai: interface endpoint chỉ là đường kết nối dịch vụ, không thay quản lý phiên/xác thực.', 'ssm ssmssh ssmprice','on-premises servers|SSH keys|machine hours','Nếu không muốn SSH keys, dùng native Session Manager shell và kiểm tra phí hybrid hiện hành theo phiên.','Pricing chính thức: bỏ Advanced Instances Tier 2026-06-30; $0.05/hybrid session từ 2026-09-30, không hourly; hoàn toàn isolated còn cần outbound/private service path.', ['B'])
put(12,'C','verified','GuardDuty EKS Protection phân tích audit logs; Runtime Monitoring bổ sung sự kiện OS, mạng và file. EventBridge chuyển finding tới SNS email, với runtime agent và loại node được hỗ trợ.', 'Sai: Security Hub tổng hợp posture/findings, không tự thu mọi runtime event.|Sai: Inspector/Detective không thay EKS audit và runtime threat detection này.|Đúng: bật cả EKS Protection và Runtime Monitoring, route findings qua EventBridge tới SNS.|Sai: cảnh báo mọi audit log không tương đương phát hiện nguy cơ runtime.', 'eks runtime gdevent','audit logs|file events|email alerts','Nếu cần audit lẫn OS/network/file, bật hai tính năng GuardDuty và xác nhận node hỗ trợ runtime agent.','Runtime Monitoring không hỗ trợ EKS Fargate; không cần bật CloudWatch audit stream riêng cho GuardDuty.')
put(13,['A','E'],'ambiguous','Dùng thing name làm client ID và policy server-side ràng buộc iot:Connect với ThingName của danh tính đã gắn thing. A/E là ý định đúng nhưng chuỗi biến của E phải sửa dấu đóng và dùng đầy đủ resource ARN.', 'Đúng khi policy xác thực cũng buộc client ID khớp thing.|Sai: Trojan có thể bỏ qua kiểm tra phía client.|Sai: AWSIoTWirelessDataAccess/principal client không phải iot:Connect resource policy phù hợp.|Sai: ClientId tự tham chiếu vẫn cho client tự chọn resource.|Đúng về ý định nếu sửa ${iot:Connection.Thing.ThingName} và ARN, với principal đã gắn thing.', 'iotclient iotthing','client ID|special characters|privilege scope','Nếu ClientId do client kiểm soát, bind Connect vào authenticated ThingName ở policy server-side.','E đóng biến bằng ) thay }; shorthand client/... thiếu ARN; literal policy không hợp lệ.', ['A','E'])
put(14,'B','verified','AWS Config configuration item là bản ghi trạng thái cấu hình phù hợp để đánh giá tác động tích lũy. Nếu chỉ muốn trạng thái cuối theo khoảng thời gian, cấu hình Daily recording; Continuous mặc định không bảo đảm chỉ một bản ghi cuối.', 'Sai: CloudTrail ghi API activity, không snapshot cấu hình tích lũy.|Đúng: xem CI mới nhất của AWS Config, chọn recording frequency phù hợp.|Sai: CloudWatch không thay resource configuration item.|Sai: Cloud Map phục vụ service discovery, không ghi trạng thái compliance.', 'config daily','configuration changes|latest configuration|cumulative impact','Nếu muốn chỉ trạng thái cấu hình mới nhất trong 24 giờ, đặt AWS Config Daily recording.','Không có cơ sở hiện hành cho khẳng định mọi thay đổi nhanh tự động bị gộp bởi Continuous recorder.')
put(15,'D','ambiguous','KMS custom CloudHSM store đáp ứng symmetric master key và CloudTrail audit. GenerateDataKeyPair không hỗ trợ custom key store, nên cần một KMS key thông thường riêng nếu còn phải tạo asymmetric data key pairs.', 'Chưa đủ: Athena truy vấn log nhưng không thay CloudTrail recorder; custom-store limitation vẫn còn.|Sai: S3 không cung cấp KMS data-key generation.|Sai: GuardDuty là threat detection, không audit mọi KMS operation.|Gần nhất: KMS/CloudHSM và CloudTrail, nhưng asymmetric pair cần key ngoài custom store.', 'hsm pair kmsaudit','custom key store|asymmetric data key pairs|audit','Nếu cần GenerateDataKeyPair, dùng symmetric KMS key thông thường để bảo vệ pair, không dùng key trong custom store.','Không lựa chọn nào thỏa nếu mọi data keys bắt buộc sinh bằng custom-store key; phân biệt key type và API capability.', ['D'])
put(16,'C','verified','Đưa CloudWatch agent vào AMI để các instance mới stream log ra CloudWatch Logs trước scale-in. Đặt retention ít nhất 365 ngày và kiểm tra retention của log group hiện có.', 'Sai: EBS riêng không tự bảo đảm không bị xóa/khả dụng sau termination.|Sai: copy mỗi ngày có thể mất log giữa hai lần copy trước scale-in.|Đúng: stream log tập trung và retention >=365 ngày.|Sai: review thủ công không cung cấp lưu trữ bền một năm.', 'cwagent','Auto Scaling group|scale-in event|1 year','Nếu log chỉ nằm trên instance Auto Scaling, stream ra dịch vụ log tập trung và đặt retention trước khi scale-in.')
put(17,'A','verified','Giới hạn S3 gateway endpoint theo cả PrincipalOrgID và ResourceOrgID để chặn principal/bucket ngoài organization trên đường ra duy nhất. Chỉ sửa instance role hoặc SCP không ngăn kẻ tấn công dùng thông tin xác thực ngoài organization qua endpoint mặc định.', 'Đúng: ràng buộc principal và tài nguyên trong org trên mọi request qua endpoint.|Sai: instance role vốn hạn chế bucket; attacker có thể dùng credentials khác.|Sai: chặn 443 làm job S3 ngừng hoạt động.|Chưa đủ: SCP không kiểm soát principal ngoài organization và Allow riêng không thay deny.', 'perimeter','default access policy|outside|exfiltrating data','Nếu attacker có thể dùng credentials khác trên máy bị xâm nhập, đặt resource perimeter ở endpoint thay vì chỉ sửa instance role.')
put(18,'A','verified','Khôi phục đúng cluster bằng PITR tới 3:14 PM của ngày cách đây 5 ngày, trước thời điểm tấn công và trong retention 14 ngày. PITR tạo cluster mới; cần quy đổi timezone đúng khi nhập timestamp.', 'Đúng: thời điểm gần nhất được nêu trước cuộc tấn công.|Sai: snapshot gần nhất có thể sau tấn công hoặc mất dữ liệu hơn PITR.|Sai: khôi phục database khác không phục hồi cluster bị ảnh hưởng.|Sai: 14 ngày gây mất dữ liệu không cần thiết.', 'pit','last known good version|14 days|3:15 PM','Nếu thời điểm bắt đầu tấn công đã biết và nằm trong retention, PITR tới ngay trước thời điểm đó.')
put(19,None,'ambiguous','CloudTrail Lake phù hợp thu thập lịch sử tổ chức, nhưng IAM user khác Identity Center user. Disable người dùng Identity Center một mình không thu hồi các AWS role session đã phát hành, nên D không đáp ứng ngay lập tức mọi account như viết.', 'Chưa đủ: IAM user chỉ thuộc một account; disable ở management account không thu hồi mọi assumed-role session.|Sai: xóa policy không giải quyết đầy đủ active role sessions, Security Hub không truy vấn mọi API log.|Sai: xóa assignments không tự thu hồi active role sessions; Logs Insights không trực tiếp query S3 trail.|Gần nhất về truy vấn: Lake đúng, nhưng identity sai phạm vi và disable đơn lẻ không revoke active sessions.', 'revokeidc lake principal','compromised IAM user|immediately|previous 7 days','Nếu danh tính dùng Identity Center, thực hiện quy trình revoke cả assignment/session và deny role sessions, rồi query CloudTrail Lake.','Không option đáp ứng literal IAM user + mọi AWS account + immediate; cần phân biệt credentials/IdC user/role session.', ['D'])
put(20,'A','verified','Inspector phát hiện lỗ hổng phần mềm trên EC2; Systems Manager Patch Manager triển khai bản vá và kiểm tra compliance. Hai dịch vụ bổ sung cho nhau để phát hiện và khắc phục.', 'Đúng: Inspector để phát hiện, Patch Manager để vá.|Sai: firewall/antivirus không thay CVE scanning và patching.|Sai: log/metric monitoring không cung cấp vulnerability scanning/remediation.|Sai: Malware Protection tìm malware, không thay package vulnerability assessment.', 'inspector patch','detect and mitigate|software vulnerabilities|EC2 instances','Nếu yêu cầu cả phát hiện CVE và khắc phục, kết hợp vulnerability scanner với Patch Manager.')
put(21,'C','verified','Macie automated discovery lấy mẫu đại diện hằng ngày để xác định bucket có dữ liệu nhạy cảm, rồi chạy discovery jobs toàn bộ phạm vi object được hỗ trợ trong bucket đó. Đây là luồng ít quản trị nhất trong các lựa chọn.', 'Sai: replicate để scan thêm chi phí và vận hành.|Sai: tự Lambda/on-upload tăng triển khai và vẫn cần discovery job phù hợp.|Đúng: automated sampling trước, full job trên bucket liên quan sau.|Sai: thêm DynamoDB/custom inventory không cần cho Macie native results.', 'maciedaily','many S3 buckets|additional scanning|LEAST administrative overhead','Nếu phải ưu tiên scan sâu trong nhiều bucket, dùng automated discovery để chọn bucket rồi chạy targeted jobs.','Full scan chỉ các object đủ điều kiện và định dạng/storage class được hỗ trợ, không mọi object/version tuyệt đối.')
put(22,'D','verified','Mã hóa snapshot bằng customer managed KMS key và cấp quyền snapshot/key cho hai account nhận. Bên nhận cần key policy cùng IAM permission để copy/restore theo cơ chế RDS hỗ trợ.', 'Sai: không thể export AWS managed KMS key material.|Sai: import vào key khác không giúp key đó giải mã ciphertext của snapshot cũ.|Sai: default AWS managed RDS key không hỗ trợ chia sẻ encrypted snapshot.|Đúng: customer key có cross-account key access và snapshot sharing.', 'snapshot','two accounts|encrypted|decrypt the snapshots','Nếu chia sẻ encrypted RDS snapshot khác account, dùng customer managed key và cấp quyền cả snapshot lẫn key.')
put(23,'A','ambiguous','require_secure_transport=ON bắt buộc TLS cho Aurora MySQL. Aurora PostgreSQL dùng rds.force_ssl, nên A chỉ đúng khi bổ sung engine MySQL mà đề hiện không nêu.', 'Đúng có điều kiện: require_secure_transport thuộc Aurora MySQL.|Sai: Kerberos xác thực không tự bắt buộc TLS cho mọi kết nối.|Sai: ACM certificate không phải cơ chế attach/enforce TLS của Aurora.|Chưa đủ: thêm proxy không tự chặn đường kết nối trực tiếp hoặc bắt buộc TLS nếu chưa cấu hình.', 'mysql postgres','Aurora cluster|all connections|in transit','Nếu Aurora MySQL, bật require_secure_transport; nếu PostgreSQL, bật rds.force_ssl.','Engine không được chỉ định; API/parameter khác giữa hai Aurora engines.', ['A'])
put(24,'C','verified','Thực thi bộ đếm theo IP trong ứng dụng bằng state dùng chung và cập nhật atomic để áp mức 3 lần trong cửa sổ trượt 5 phút. WAF rate-based rule hiện có minimum 10 và chỉ xấp xỉ, nên không thể cấu hình chính xác 3.', 'Sai: WAF Limit nhỏ nhất hiện là 10, không phải 3.|Sai: alert/Lambda không phải synchronous read quota enforcement.|Đúng có điều kiện: counter phải chia sẻ across EC2 và enforce cửa sổ trượt/atomic.|Sai: TTL xóa bất đồng bộ và provisioned capacity không tạo quota per IP.', 'wafrate','stateless application|3 times|5-minute period','Nếu hạn mức nhỏ hơn WAF minimum hoặc cần chính xác, enforce bằng application counter dùng chung.','Không dùng số minimum WAF 100 đã lỗi thời; stateless fleet không được dùng counter local per instance.')
put(25,'B','verified','B deny inbound 3306 trước allow inbound ephemeral 1024–65535, đồng thời allow outbound 443. Thứ tự này vừa chặn MySQL vừa cho phép response TLS trong NACL stateless.', 'Sai: inbound 443 không cho return traffic tới ephemeral port của client.|Đúng: deny 3306 số nhỏ hơn rule allow ephemeral; outbound 443.|Sai: allow 1024–65535 trước deny 3306 sẽ match 3306 và bỏ qua deny sau.|Sai: không mở inbound ephemeral nên response TLS bị chặn.', 'nacl','custom network ACL|port 443|port 3306','Nếu dùng NACL cho outbound HTTPS, mở inbound ephemeral và đặt deny đặc biệt trước range allow.')
put(26,'D','ambiguous','Secrets Manager với rotation và IAM task role có quyền tối thiểu là thiết kế phù hợp nhất. Inline policy cũng hợp lệ khi gắn vào task role; role chỉ cô lập theo task, không bảo đảm chỉ một container trong cùng task hay ngăn DBA chia sẻ credentials họ đã biết.', 'Sai: Parameter Store không cung cấp RDS rotation native; EC2 instance profile không thay task role.|Có thể đúng nếu inline policy gắn task role và rotation bật; không thể loại chỉ vì inline policy.|Sai: Parameter Store mã hóa không tự cung cấp rotation yêu cầu.|Tốt nhất: Secrets Manager rotation và task IAM role, với giới hạn task/container và DBA access.', 'taskrole rotate','rotated periodically|application only|plaintext','Nếu nhiều container cần quyền khác nhau, tách task và role; chỉ cấp GetSecretValue cho role ứng dụng, không DBA.','B mô tả inline policy chưa xác định nơi attach; D không đảm bảo isolation giữa containers; rotation phải cấu hình, không mặc định.', ['B','D'])
put(27,['A','C'],'verified','KMS interface endpoint với private DNS đưa kết nối vào private endpoint; key policy ràng buộc SourceVpce buộc request qua endpoint đó. Để cưỡng chế thật sự, dùng deny ngoài endpoint hoặc loại bỏ mọi đường allow thay thế.', 'Đúng: SourceVpce kiểm tra endpoint ID, với policy enforce đầy đủ.|Sai: thêm virtual private gateway không tự cung cấp KMS private endpoint.|Đúng: endpoint và private DNS cho đường gọi private.|Sai: import key material không thay đường network của KMS API.|Sai: SourceIp 10.0.0.0/16 không nhận diện request qua interface endpoint.', 'vpce dns','within the AWS network|public service endpoints','Nếu policy phải bắt buộc qua VPCE, deny request không có SourceVpce phù hợp và xét các service integration cần ngoại lệ.')
put(28,'D','verified','Thu hồi các session của IAM role gắn instance profile để credentials bị đánh cắp không còn gọi AWS API. Thay inbound security group không chặn API call thực hiện từ bên ngoài bằng credentials đó.', 'Sai: inbound network rule không vô hiệu hóa AWS credentials bị đánh cắp.|Sai: inventory không ngăn attacker dùng token.|Sai: vulnerability scan không thu hồi token.|Đúng: revoke active role sessions issued trước thời điểm thu hồi.', 'revokerole','InstanceCredentialExfiltration|API access keys|first step','Nếu instance credentials bị dùng ngoài AWS, revoke role sessions trước rồi tiếp tục xử lý nguồn xâm nhập.','Revoke có thể ảnh hưởng ứng dụng; không ngăn attacker lấy credentials mới nếu instance vẫn bị kiểm soát.')
put(29,'B','verified','SSE-KMS với customer managed key chia quyền S3 cho operations và quyền decrypt cho security. Đọc plaintext cần đồng thời quyền GetObject và kms:Decrypt, nên một bên cấu hình sai không tự đủ quyền.', 'Sai: SSE-S3 không có customer KMS policy riêng để chia hai tầng quyền.|Đúng: enforce customer-key SSE-KMS và tách S3/key policy administration.|Sai: SSE-S3 do S3 quản lý key không đáp ứng tách quyền decrypt này.|Sai: SSE-C dùng khóa khách hàng cung cấp, không có KMS key policy như mô tả.', 'ssekms','separate the duties|plaintext data|encryption keys','Nếu cần hai nhóm cùng cho phép mới đọc được plaintext, dùng customer-key SSE-KMS và tách quyền S3/KMS.')
put(30,'A','verified','Chọn security account làm delegated administrator cho Macie và Security Hub để quản lý discovery xuyên organization và tổng hợp findings. Bật publication sensitive-data findings theo account/Region cần thiết, vì Macie không gửi loại này mặc định.', 'Đúng: Macie phát hiện S3 sensitive data và Security Hub tổng hợp findings.|Sai: Inspector không phân loại dữ liệu nhạy cảm trong S3.|Sai: Inspector vẫn không tạo sensitive-data inventory.|Sai: Trusted Advisor không là đích tích hợp Macie sensitive findings thay Security Hub.', 'macieorg maciepublish','across the organization|single location|sensitive data','Nếu muốn Macie sensitive findings trong Security Hub, bật publication loại này và kiểm tra từng account/Region.','Publication sensitive findings opt-in; delegated administrator không tự thay publication settings mọi member account.')
put(31,'B','verified','GuardDuty không thấy DNS requests dùng custom resolver như OpenDNS, nên không sinh DNS finding tương ứng để gửi Security Hub. GuardDuty tự thu nguồn log nền tảng; không cần tự bật VPC Flow Logs cho nó.', 'Sai: GuardDuty thu nguồn log độc lập, không cần khách tự tạo Flow Logs.|Đúng: custom DNS không được foundational DNS monitoring hỗ trợ.|Sai: tích hợp GuardDuty/Security Hub tự có khi hai dịch vụ đã bật; không cần forward custom.|Sai: hệ thống chỉ một Region, không có vấn đề cross-Region như phương án.', 'gdsource gdhub','DNS requests|test domain|single AWS Region','Nếu test DNS finding, dùng AWS resolver và domain/test threat-list phù hợp loại finding.','example.com tự thân không chứng minh malicious domain; cần biết test/threat-list đã cấu hình.')
put(32,['B','C'],'verified','Đặt độ dài mật khẩu ở Cognito user pool cho người dùng local và ở Active Directory cho danh tính federation. IAM password policy không áp lên password của external IdP.', 'Sai: IAM policy chỉ áp mật khẩu IAM users, không AD-federated users.|Đúng: Cognito password policy cho local user database.|Đúng: AD kiểm soát password của người dùng được AD xác thực.|Sai: SCP giới hạn AWS permissions, không validate password login của AD/Cognito.|Sai: IAM condition không cung cấp minimum-password-length login chung này.', 'cognitopwd iampwd','Active Directory|user database|required minimum length','Nếu danh tính federation, sửa password policy tại IdP thực sự xác thực người dùng.','Cognito vốn có minimum length >=6; no required minimum là premise không chính xác nếu hiểu theo nghĩa không có bất kỳ minimum nào.')
put(33,'C','verified','WAF rule match User-Agent của emulator và block request tới ALB, với default allow cho request khác. Dấu hiệu này xử lý nguồn IP phân tán nhưng attacker có thể đổi User-Agent nên đây là giảm thiểu theo marker đã cho.', 'Sai: thông báo số lần login không trực tiếp block attack.|Sai: security group không có deny hoặc kiểm tra User-Agent.|Đúng: WAF header string match với Block chặn marker được nêu.|Sai: allow các User-Agent đã biết không tự block marker này và dễ chặn login hợp lệ.', 'string sg','many IP addresses|user agent string|legitimate logins','Nếu attack có marker HTTP header ổn định, dùng WAF block marker và kiểm tra false positives.','User-Agent spoofable; không nên diễn giải đây là biện pháp chặn mọi credential stuffing.')
put(34,'A','verified','Đặt hai EC2 sau ALB, gắn WAF SQL injection rule rồi chuyển DNS khi sẵn sàng; hạn chế EC2 chỉ nhận web traffic từ ALB để tránh bypass. Cách này giữ hai backend đang hoạt động và không cần sửa legacy code trong 24 giờ.', 'Đúng: ALB/WAF trước hai backend và chuyển DNS có kiểm soát.|Chưa đủ: CloudFront một EC2 làm giảm HA và direct EC2 path cần chặn riêng.|Sai: tự vá legacy source khó đạt yêu cầu ít công sức trong 24 giờ.|Sai: WAF không gắn trực tiếp EC2; đóng DB port không ngăn SQLi qua ứng dụng.', 'sqli wafresources','24 hours|least amount of effort|normal operations','Nếu cần giảm SQLi nhanh cho legacy app, WAF ở ALB và chặn mọi direct-backend bypass.','WAF giảm thiểu theo rule; cần staging/rule validation với mẫu attack và traffic hợp lệ.')
put(35,'B','verified','Chạy eic_harvest_hostkeys để cập nhật host keys mới vào trusted host-key database của EC2 Instance Connect. Đây là host key của server, khác key pair đăng nhập của client.', 'Sai: KMS key không quản lý SSH host-key trust của Instance Connect.|Đúng: cập nhật host-key database bằng eic_harvest_hostkeys.|Sai: SSM policy không cập nhật EC2 Instance Connect host-key trust.|Sai: tạo login key pair mới không sửa server host key bị stale.', 'host','rotated the host keys|failed host key validation','Nếu EC2 Instance Connect lỗi sau host-key rotation, harvest host keys mới trên instance.')
put(36,'C','verified','Dùng Macie managed data identifiers để phát hiện dữ liệu nhạy cảm trong S3 và EventBridge chuyển findings tới SNS topic hiện có. Đây là tích hợp native ít triển khai hơn tự viết scanner.', 'Sai: Config đánh giá cấu hình resource, không phân loại nội dung S3.|Sai: custom Lambda scanner cần tự xây logic và vận hành.|Đúng: Macie findings → EventBridge → SNS.|Sai: GuardDuty phát hiện threat, không discovery nội dung sensitive data.', 'macie','sensitive data|existing|SNS','Nếu đã có SNS topic, route Macie sensitive-data findings bằng EventBridge và kiểm tra topic policy/subscription.')

records=[]
for q in qs:
    r=D[q['id']]
    prefix=q['id']+':'
    a=r['independent_answer']
    if isinstance(a,str): a=prefix+a
    elif isinstance(a,list): a=[prefix+x for x in a]
    elif isinstance(a,dict): a={prefix+k:prefix+v if v else None for k,v in a.items()}
    ids=[c['id'] for c in q.get('choices',[])]
    if q['type']=='ordering': ids=[c['id'] for c in q['interaction']['steps']]
    if q['type']=='matching': ids=[c['id'] for c in q['interaction']['prompts']]+[c['id'] for c in q['interaction']['responses']]
    assert len(ids)==len(r['reasons']), (q['id'],ids,r['reasons'])
    # Keywords must be exact original source phrases, not translations or inferred labels.
    stem=' '.join(b.get('text','') for b in q['stem'])
    assert len(r['keywords'])<=3
    assert all(k in stem for k in r['keywords']), (q['id'],r['keywords'])
    r.update(id=q['id'],question_type=q['type'],independent_answer=a,concluded_at_utc=now,
        confidence='high' if r['status']=='verified' else 'medium',
        per_option=[{'id':oid,'verdict_reason_vi':why,'source_ids':r['source_ids']} for oid,why in zip(ids,r.pop('reasons'))],
        citations=[S[x] for x in r['source_ids']])
    if r['candidates'] is not None: r['candidates']=[prefix+x for x in r['candidates']]
    records.append(r)
out={'scope':'Q001-Q036','method':'Independent solve from blind questions, all source images, and primary AWS documentation; keys/reviews not read before this persistence.',
    'blinded':True,'answer_key_exposure_before_persistence':False,'persisted_at_utc':now,
    'primary_sources_opened_before_persistence':list(S.values()),'questions':records}
(ROOT/'independent.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'count':len(records),'option_units':sum(len(r['per_option']) for r in records),'timestamp':now,'statuses':{s:sum(r['status']==s for r in records) for s in ['verified','ambiguous','unresolved']}},ensure_ascii=False))
